"""Album-layout metadata emitter for the mastering pipeline
(#290 phase 5, step 7).

Pure-Python string + dict manipulation — no I/O. The layout module
produces ``LAYOUT.md``: a human-readable markdown file with a machine-
parseable YAML transitions block, one entry per adjacent track pair.

MVP emits one default transition per pair (``gap`` or ``gapless``,
controlled by the album README's ``layout.default_transition``
frontmatter field). Energy / tempo-based auto-detection is future work.
"""

from __future__ import annotations

import re
from typing import Any

import yaml

# Defaults from #290 issue section "Layout & transitions".
DEFAULT_TRANSITION: dict[str, Any] = {
    "mode": "gap",
    "gap_ms": 1500,
    "tail_fade_ms": 100,
    "head_fade_ms": 50,
}

GAPLESS_TRANSITION: dict[str, Any] = {
    "mode": "gapless",
    "gap_ms": 0,
    "tail_fade_ms": 0,
    "head_fade_ms": 0,
}

_MODE_TO_DEFAULTS: dict[str, dict[str, Any]] = {
    "gap":     DEFAULT_TRANSITION,
    "gapless": GAPLESS_TRANSITION,
}


class LayoutError(ValueError):
    """Raised when layout inputs are invalid (unknown mode, malformed input)."""


def parse_layout_yaml(markdown: str) -> list[dict[str, Any]]:
    """Extract and parse the YAML transitions block from a LAYOUT.md string.

    Args:
        markdown: Full text content of a LAYOUT.md file.

    Returns:
        List of transition dicts parsed from the yaml fenced block, or an
        empty list if the block is absent, malformed, or contains no
        ``transitions`` list.
    """
    try:
        match = re.search(r"```yaml\n(.*?)```", markdown, re.DOTALL)
        if not match:
            return []
        parsed = yaml.safe_load(match.group(1))
        transitions = parsed.get("transitions") if isinstance(parsed, dict) else None
        return transitions if isinstance(transitions, list) else []
    except Exception:  # noqa: BLE001
        return []


def compute_transitions(
    track_filenames: list[str],
    *,
    default_transition: str = "gap",
    prior_transitions: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """Build one transition per adjacent pair using *default_transition*.

    Hand-edited entries from a previous LAYOUT.md are preserved when
    *prior_transitions* is supplied: any ``(from, to)`` pair present in
    *prior_transitions* replaces the freshly-computed default for that pair.
    Pairs that no longer exist (track removed) are silently dropped.

    Args:
        track_filenames:    Ordered list of delivery WAV basenames.
        default_transition: Either ``"gap"`` or ``"gapless"``.
        prior_transitions:  Parsed transitions from an existing LAYOUT.md,
                            as returned by :func:`parse_layout_yaml`.  Pass
                            ``None`` (default) to skip preservation.

    Returns:
        List of transition dicts in adjacent-pair order. Empty list when
        *track_filenames* has fewer than 2 entries.

    Raises:
        LayoutError: Unknown *default_transition* value.
    """
    if default_transition not in _MODE_TO_DEFAULTS:
        raise LayoutError(
            f"Unknown transition mode {default_transition!r}; "
            f"expected one of {sorted(_MODE_TO_DEFAULTS)}"
        )

    if len(track_filenames) < 2:
        return []

    defaults = _MODE_TO_DEFAULTS[default_transition]
    transitions: list[dict[str, Any]] = []
    for from_name, to_name in zip(track_filenames[:-1], track_filenames[1:]):
        transitions.append({
            "from":          from_name,
            "to":            to_name,
            "mode":          defaults["mode"],
            "gap_ms":        defaults["gap_ms"],
            "tail_fade_ms":  defaults["tail_fade_ms"],
            "head_fade_ms":  defaults["head_fade_ms"],
        })

    if prior_transitions:
        prior_lookup: dict[tuple[str, str], dict[str, Any]] = {
            (t["from"], t["to"]): t
            for t in prior_transitions
            if "from" in t and "to" in t
        }
        transitions = [
            prior_lookup.get((t["from"], t["to"]), t)
            for t in transitions
        ]

    return transitions


def render_layout_markdown(
    album_slug: str,
    transitions: list[dict[str, Any]],
) -> str:
    """Render LAYOUT.md content as a markdown string.

    The yaml fenced block is the machine-readable source of truth;
    surrounding prose is for humans reviewing the album delivery.
    """
    yaml_block = yaml.safe_dump(
        {"transitions": transitions},
        sort_keys=False,
        default_flow_style=False,
    )
    # Trim trailing newline from safe_dump for a clean fenced block.
    yaml_block = yaml_block.rstrip("\n")

    header = (
        f"# Album Layout\n\n"
        f"<!-- Auto-generated by master_album (#290 step 7). Hand-edits\n"
        f"     survive re-masters only for transitions where the track\n"
        f"     filenames still match. -->\n\n"
        f"**Album:** `{album_slug}`\n\n"
        f"## Transitions\n\n"
    )

    if not transitions:
        body = (
            "Single-track album — no transitions to emit.\n\n"
            "```yaml\n"
            "transitions: []\n"
            "```\n"
        )
    else:
        body = f"```yaml\n{yaml_block}\n```\n"

    return header + body
