"""Harmonic excitation: generate synthetic upper harmonics to add brightness
and presence to dark-material stems.

Algorithm: apply tanh soft-saturation to the full signal, then high-pass both
the saturated and original signals, subtract to isolate the nonlinear distortion
products above the cutoff, attenuate to the requested amount, and mix back into
the source.

Compared to a pure bandpass-then-saturate approach, operating on the full
signal and differencing out the original gives stronger harmonic generation
because all of the input energy (including the dominant low frequencies)
participates in the nonlinear saturation. The HP subtraction step ensures that
only new harmonics above ``freq_range[0]`` are added.

Used by the polish stage when a stem is classified ``already_dark`` (high_mid
band_energy < 10 %) AND the preset's ``adm_aware_excitation`` flag is on.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy import signal


def apply_harmonic_excitation(
    data: Any,
    rate: int,
    amount_db: float,
    freq_range: tuple[float, float] = (600.0, 12000.0),
    drive: float = 20.0,
) -> Any:
    """Add synthetic upper harmonics to ``data`` via saturate-hipass-diff-mix.

    Algorithm:
    1. Soft-saturate the full signal via ``tanh(drive * x) / drive``.
    2. High-pass both the saturated signal and the original at ``freq_range[0]``.
    3. Subtract HP(original) from HP(saturated) to isolate the new harmonic
       content generated by the nonlinearity above the cutoff.
    4. Attenuate the new harmonics by ``amount_db`` gain.
    5. Mix back into the original signal.

    By operating on the full-band signal before filtering, the saturation has
    access to all input energy — including dominant low-frequency content that
    would otherwise generate only weak harmonics if first bandpassed. The
    differencing step (HP_sat - HP_orig) ensures only *new* harmonic content
    is added; no spectral energy below ``freq_range[0]`` leaks into the mix.

    Args:
        data: Stereo or mono numpy array (float).
        rate: Sample rate in Hz.
        amount_db: Excitation intensity in dB. ``<= 0`` is a no-op;
            typical useful range 1.0-4.0 dB. Above 6 dB becomes audible
            as processing.
        freq_range: (low, high) Hz of the excitation output band. Harmonics
            below ``low`` are discarded. Defaults to (600, 12000) which covers
            the presence/air band while reaching low enough to affect dark-
            material stems that lack high-mid content.
        drive: tanh saturation drive. Higher drive → more aggressive harmonic
            generation. Default 20.0 is tuned so that dark-material stems at
            typical Suno output levels (−18 to −20 dBFS RMS) receive a
            measurable presence boost at low ``amount_db`` settings.

    Returns:
        Excited signal with the same shape and dtype as ``data``.
    """
    if amount_db <= 0.0:
        return data

    low, high = freq_range
    nyq = rate / 2.0
    # Clamp high to stay below Nyquist.
    if high >= nyq:
        high = nyq - 1.0
    if low <= 0 or low >= high:
        # Degenerate band — no-op.
        return data

    # Soft saturation: tanh compresses peaks and generates odd-order harmonics
    # from the full-band signal so that dominant low-frequency content
    # contributes to harmonic generation.
    saturated = np.tanh(drive * data) / drive

    # High-pass both signals at the lower excitation band boundary.
    # Using sosfiltfilt (zero-phase) to avoid phase delay artifacts.
    sos_hp = signal.butter(4, low / nyq, btype="high", output="sos")
    hp_saturated = signal.sosfiltfilt(sos_hp, saturated, axis=0)
    hp_original = signal.sosfiltfilt(sos_hp, data, axis=0)

    # Difference isolates only the *new* harmonics created by the nonlinearity.
    # HP(sat) - HP(orig) = HP(sat - orig) by linearity of the HP filter,
    # which equals HP(distortion_products).
    new_harmonics = hp_saturated - hp_original

    gain_linear = 10.0 ** (amount_db / 20.0)
    return data + new_harmonics * gain_linear
